### ISSUE TITLE
chamber module dependencies

### ISSUE THREAD

**Issue by mmuehlberger** [cloudposse/terraform-root-modules#132]
The [cloudposse/reference-architectures](https://github.com/cloudposse/reference-architectures) use the `chamber` module for bootstrapping, which, since adding https://github.com/cloudposse/terraform-root-modules/pull/120, has a lot of dependencies on resources that don't exist yet in the process.

_Context: I'm trying to use the current version of `terraform-root-modules` with `reference-architectures`._

**Comment by osterman** [comment]
@mmuehlberger you are correct that reference-architectures has not been tested with the latest versions of our root-modules. The S3 support for chamber is very new as it's something we are currently working on for a client. Our reference-architectures will lag because regression tests on AWS accounts are nearly impossible due to the need to manually accept the T&C after programmatically generating the account, in order to tear down the account.
